name: Artifact

on: [push]

env:
  ARTIFACT_NAME: myartifact
jobs:
  main:
    runs-on: unbuntu-latest
    steps:
       - name: checkout the code
         uses: checkout@v2
       - name: upload the artifact
         uses: upload-artifact@v2
         with:
           name: ${{env.ARTIFACT_NAME}}
           path: .
           
